language: java
jdk:
  - openjdk11
branches:
  only:
    - main
addons:
  mariadb: '10.0'
before_install:
  - cd back
  - chmod +x mvnw


#travis ci server home
cache:
  directories:
    - $HOME/.m2

before_deploy:
  - zip -r pilas-springboot-webservice ./*
  - mkdir -p deploy
  - mv pilas-springboot-webservice.zip deploy/pilas-springboot-webservice.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

    bucket: pilas-springboot-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private

    local_dir: deploy
    wait-until-deployed: true
    on:
      all_branches: true


  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

    bucket: pilas-springboot-build
    key: pilas-springboot-webservice.zip
    bundle_type: zip
    application: pilas-springboot-webservice

    deployment_group: pilas-springboot-webservice-group

    region: ap-northeast-2
    wait-until-deployed: true
    on:
      all_branches: true

notifications:
  email:
    recipients:
      - kebinkorea@gmail.com