language: java
jdk:
  - openjdk11
branches:
  only:
    - main

before_install:
  - cd back
  - chmod +x mvnw
  - mvn clean install

#travis ci server home
cache:
  directories:
    - $HOME/.m2
notifications:
  email:
    recipients:
      - kebinkorea@gmail.com