
server:
  port: 8080
  servlet:
    context-path: /

spring:
#  mvc:
#    view:
#      prefix: /WEB-INF/views/
#      suffix: .jsp
  mail:
    host: smtp.gmail.com
    port: 587
    username: kebinkorea@gmail.com
    password: Dmsquf0714!
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/pila?serverTimezone=Asia/Seoul
    username: user1
    password: user1

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate.format_sql: true

  jackson:
    serialization:
      fail-on-empty-beans: false

  http:
    encoding:

#  security:
#    oauth2:
#      client:
#        registration:
#          google: # /oauth2/authorization/google 이 주소를 동작하게 한다.
#            client-id: 588000139755-i5inq6jei66hsugf2ilef0bqu4ev7rns.apps.googleusercontent.com
#            client-secret: 0Vd_EVhplFR1kNfyU7fbZwWU
#            scope:
#              - email
#              - profile
jwt:
  header: Authorization
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity: 86400

logging:
  level:
    com.keb: DEBUG
