language: java
jdk:
  - openjdk11
before_install:
  - chmod +x mvnw
branches:
  only:
    - master


#travis ci server home
cache:
  directories:
    - "$HOME/.m2/repository"


notifications:
  email:
    recipients:
      - kebinkorea@gmail.com